/* ==========================================================================
   PRINTERSVAULT — MASTER PRODUCT DATASET (44 PRODUCTS)
   Source of Truth: Centralized E-Commerce Catalog matching Smart ePrint
   ========================================================================== */

const PRODUCTS = [
  {
    "id": "PV-001",
    "numericId": 1,
    "sku": "PV-001",
    "name": "Brother DCP-L2640DW Compact Wireless Black & White Laser Printer",
    "category": "Laser Printers",
    "brand": "Brother",
    "price": 209.99,
    "oldPrice": 239.99,
    "regularPrice": 239.99,
    "salePrice": 209.99,
    "discount": 13,
    "rating": "4.6",
    "reviews": 52,
    "badge": "Laser Pro",
    "stock": true,
    "printTech": "Monochrome Laser",
    "type": "printer",
    "svgAccent": "#2563EB",
    "image": "images/build.png",
    "description": "The Brother DCP-L2640DW offers reliable, fast monochrome laser printing, copy and scan functions. Designed for compact home office environments with wireless connectivity and automatic duplex printing.",
    "features": [
      "Print speeds up to 36 pages per minute",
      "Wireless, Ethernet, and USB connectivity",
      "Automatic 2-sided duplex printing",
      "250-sheet capacity paper tray",
      "Compact footprint ideal for small spaces"
    ],
    "specifications": {
      "Print Technology": "Monochrome Laser",
      "Functions": "Print, Copy, Scan",
      "Brand": "Brother",
      "Category": "Laser Printers",
      "Connectivity": "Wireless (Wi-Fi), USB 2.0, Mobile App Support",
      "Duplex Printing": "Automatic 2-Sided",
      "Paper Handling": "250-sheet capacity paper tray"
    },
    "slug": "brother-dcp-l2640dw-compact-wireless-black-white-laser-printer"
  },
  {
    "id": "PV-002",
    "numericId": 2,
    "sku": "PV-002",
    "name": "Brother HL-L2405W Compact Wireless Black & White Laser Printer",
    "category": "Laser Printers",
    "brand": "Brother",
    "price": 139.99,
    "oldPrice": 149.99,
    "regularPrice": 149.99,
    "salePrice": 139.99,
    "discount": 7,
    "rating": "4.7",
    "reviews": 59,
    "badge": "Laser Pro",
    "stock": true,
    "printTech": "Monochrome Laser",
    "type": "printer",
    "svgAccent": "#2563EB",
    "image": "images/build.png",
    "description": "An affordable, compact wireless black and white laser printer engineered for fast document printing with crisp text output.",
    "features": [
      "Print speeds up to 30 ppm",
      "Built-in wireless networking & Wi-Fi Direct",
      "250-sheet adjustable paper tray",
      "High-yield replacement toner option"
    ],
    "specifications": {
      "Print Technology": "Monochrome Laser",
      "Functions": "Print Only",
      "Brand": "Brother",
      "Category": "Laser Printers",
      "Connectivity": "Wireless (Wi-Fi), USB 2.0, Mobile App Support",
      "Duplex Printing": "Manual",
      "Paper Handling": "250-sheet adjustable paper tray"
    },
    "slug": "brother-hl-l2405w-compact-wireless-black-white-laser-printer"
  },
  {
    "id": "PV-003",
    "numericId": 3,
    "sku": "PV-003",
    "name": "Brother MFC-L2820DW Compact Wireless Black & White Printer",
    "category": "Laser Printers",
    "brand": "Brother",
    "price": 264.99,
    "oldPrice": 279.99,
    "regularPrice": 279.99,
    "salePrice": 264.99,
    "discount": 5,
    "rating": "4.8",
    "reviews": 66,
    "badge": "Laser Pro",
    "stock": true,
    "printTech": "Monochrome Laser",
    "type": "printer",
    "svgAccent": "#2563EB",
    "image": "images/build.png",
    "description": "Compact wireless monochrome laser all-in-one printer featuring a 2.7-inch color touchscreen, 50-sheet automatic document feeder, and robust wireless printing.",
    "features": [
      "Fast print speeds up to 34 ppm",
      "2.7-inch color touchscreen display",
      "50-sheet auto document feeder (ADF)",
      "Wireless, Ethernet & mobile device printing"
    ],
    "specifications": {
      "Print Technology": "Monochrome Laser",
      "Functions": "Print, Copy, Scan, Fax",
      "Brand": "Brother",
      "Category": "Laser Printers",
      "Connectivity": "Wireless (Wi-Fi), USB 2.0, Mobile App Support",
      "Duplex Printing": "Manual",
      "Paper Handling": "50-sheet auto document feeder (ADF)"
    },
    "slug": "brother-mfc-l2820dw-compact-wireless-black-white-printer"
  },
  {
    "id": "PV-004",
    "numericId": 4,
    "sku": "PV-004",
    "name": "Brother MFC-L3720CDW Wireless Color Laser Printer",
    "category": "Laser Printers",
    "brand": "Brother",
    "price": 459.99,
    "oldPrice": 479.99,
    "regularPrice": 479.99,
    "salePrice": 459.99,
    "discount": 4,
    "rating": "4.9",
    "reviews": 73,
    "badge": "Laser Pro",
    "stock": true,
    "printTech": "Color Digital Laser",
    "type": "printer",
    "svgAccent": "#2563EB",
    "image": "images/build.png",
    "description": "Delivers vibrant digital color printing, copying, scanning, and faxing. Equipped with wireless networking and automatic two-sided printing for efficient workflow.",
    "features": [
      "Print speeds up to 19 ppm (Color & Black)",
      "Wireless 802.11b/g/n & Ethernet interfaces",
      "3.5-inch color touchscreen",
      "250-sheet max paper tray capacity"
    ],
    "specifications": {
      "Print Technology": "Color Digital Laser",
      "Functions": "Print, Copy, Scan, Fax",
      "Brand": "Brother",
      "Category": "Laser Printers",
      "Connectivity": "Wireless (Wi-Fi), USB 2.0, Mobile App Support",
      "Duplex Printing": "Manual",
      "Paper Handling": "250-sheet max paper tray capacity"
    },
    "slug": "brother-mfc-l3720cdw-wireless-color-laser-printer"
  },
  {
    "id": "PV-005",
    "numericId": 5,
    "sku": "PV-005",
    "name": "Brother MFC-L3780CDW Wireless Color Laser Printer",
    "category": "Laser Printers",
    "brand": "Brother",
    "price": 569.99,
    "oldPrice": 599.99,
    "regularPrice": 599.99,
    "salePrice": 569.99,
    "discount": 5,
    "rating": "4.5",
    "reviews": 80,
    "badge": "Laser Pro",
    "stock": true,
    "printTech": "Color Digital Laser",
    "type": "printer",
    "svgAccent": "#2563EB",
    "image": "images/build.png",
    "description": "High-performance wireless color laser printer with advanced security options, fast print speeds, single-pass duplex scanning, and NFC tap-to-print capability.",
    "features": [
      "Print speeds up to 31 ppm color and monochrome",
      "Single-pass duplex scanning & copying",
      "3.5-inch color touchscreen display",
      "Advanced enterprise security features"
    ],
    "specifications": {
      "Print Technology": "Color Digital Laser",
      "Functions": "Print, Copy, Scan, Fax",
      "Brand": "Brother",
      "Category": "Laser Printers",
      "Connectivity": "Wireless (Wi-Fi), USB 2.0, Mobile App Support",
      "Duplex Printing": "Automatic 2-Sided",
      "Paper Handling": "Standard Input Tray"
    },
    "slug": "brother-mfc-l3780cdw-wireless-color-laser-printer"
  },
  {
    "id": "PV-006",
    "numericId": 6,
    "sku": "PV-006",
    "name": "Brother Work Smart Wireless Color All-In-One Inkjet Printer",
    "category": "Inkjet Printers",
    "brand": "Brother",
    "price": 99.99,
    "oldPrice": 109.99,
    "regularPrice": 109.99,
    "salePrice": 99.99,
    "discount": 9,
    "rating": "4.6",
    "reviews": 87,
    "badge": "Ink Tank",
    "stock": true,
    "printTech": "Color Inkjet",
    "type": "printer",
    "svgAccent": "#2563EB",
    "image": "images/build.png",
    "description": "Versatile, compact wireless color inkjet printer designed for home office needs with mobile printing support and low-cost page yield.",
    "features": [
      "Wireless printing from smartphone, tablet, laptop",
      "Compact space-saving design",
      "Automatic 2-sided printing",
      "Page Gauge ink tracking technology"
    ],
    "specifications": {
      "Print Technology": "Color Inkjet",
      "Functions": "Print, Copy, Scan",
      "Brand": "Brother",
      "Category": "Inkjet Printers",
      "Connectivity": "Wireless (Wi-Fi), USB 2.0, Mobile App Support",
      "Duplex Printing": "Automatic 2-Sided",
      "Paper Handling": "Standard Input Tray"
    },
    "slug": "brother-work-smart-wireless-color-all-in-one-inkjet-printer"
  },
  {
    "id": "PV-007",
    "numericId": 7,
    "sku": "PV-007",
    "name": "Brother MFC-L2710DW Compact Wireless Monochrome Laser All-In-One Printer",
    "category": "Laser Printers",
    "brand": "Brother",
    "price": 229.99,
    "oldPrice": 249.99,
    "regularPrice": 249.99,
    "salePrice": 229.99,
    "discount": 8,
    "rating": "4.7",
    "reviews": 94,
    "badge": "Laser Pro",
    "stock": true,
    "printTech": "Monochrome Laser",
    "type": "printer",
    "svgAccent": "#2563EB",
    "image": "images/build.png",
    "description": "Reliable monochrome laser all-in-one printer with 50-sheet ADF, automatic duplexing, and versatile wireless connectivity options.",
    "features": [
      "Print speeds up to 32 ppm",
      "50-sheet capacity automatic document feeder",
      "250-sheet paper capacity",
      "Multi-page copying and faxing"
    ],
    "specifications": {
      "Print Technology": "Monochrome Laser",
      "Functions": "Print, Copy, Scan, Fax",
      "Brand": "Brother",
      "Category": "Laser Printers",
      "Connectivity": "Wireless (Wi-Fi), USB 2.0, Mobile App Support",
      "Duplex Printing": "Manual",
      "Paper Handling": "50-sheet capacity automatic document feeder"
    },
    "slug": "brother-mfc-l2710dw-compact-wireless-monochrome-laser-all-in-one-printer"
  },
  {
    "id": "PV-008",
    "numericId": 8,
    "sku": "PV-008",
    "name": "Canon imageCLASS D1650 Wireless Monochrome Laser Multifunction Printer",
    "category": "Laser Printers",
    "brand": "Canon",
    "price": 499.99,
    "oldPrice": 569.99,
    "regularPrice": 569.99,
    "salePrice": 499.99,
    "discount": 12,
    "rating": "4.8",
    "reviews": 101,
    "badge": "Laser Pro",
    "stock": true,
    "printTech": "Monochrome Laser",
    "type": "printer",
    "svgAccent": "#E30613",
    "image": "images/build.png",
    "description": "Heavy-duty commercial monochrome laser multifunction printer designed for high-volume workgroups requiring ultra-fast print speeds and expandable paper capacity.",
    "features": [
      "Print speeds up to 45 ppm",
      "First print out in approximately 6.2 seconds",
      "5-inch customizable color touchscreen",
      "Expandable paper capacity up to 2,300 sheets"
    ],
    "specifications": {
      "Print Technology": "Monochrome Laser",
      "Functions": "Print, Copy, Scan, Fax",
      "Brand": "Canon",
      "Category": "Laser Printers",
      "Connectivity": "Wireless (Wi-Fi), USB 2.0, Mobile App Support",
      "Duplex Printing": "Manual",
      "Paper Handling": "Expandable paper capacity up to 2,300 sheets"
    },
    "slug": "canon-imageclass-d1650-wireless-monochrome-laser-multifunction-printer"
  },
  {
    "id": "PV-009",
    "numericId": 9,
    "sku": "PV-009",
    "name": "Canon imageCLASS MF753CDW Wireless Color Laser Printer",
    "category": "Laser Printers",
    "brand": "Canon",
    "price": 709.99,
    "oldPrice": 749.99,
    "regularPrice": 749.99,
    "salePrice": 709.99,
    "discount": 5,
    "rating": "4.9",
    "reviews": 108,
    "badge": "Laser Pro",
    "stock": true,
    "printTech": "Color Laser",
    "type": "printer",
    "svgAccent": "#E30613",
    "image": "images/build.png",
    "description": "Feature-rich color laser printer built for small to mid-size businesses. Provides brilliant color output, single-pass duplex scanning, and application library custom shortcuts.",
    "features": [
      "Print speeds up to 35 ppm color/monochrome",
      "5-inch color touchscreen display",
      "Single-pass 2-sided scanning",
      "Wi-Fi Direct & mobile app printing"
    ],
    "specifications": {
      "Print Technology": "Color Laser",
      "Functions": "Print, Copy, Scan, Fax",
      "Brand": "Canon",
      "Category": "Laser Printers",
      "Connectivity": "Wireless (Wi-Fi), USB 2.0, Mobile App Support",
      "Duplex Printing": "Automatic 2-Sided",
      "Paper Handling": "Standard Input Tray"
    },
    "slug": "canon-imageclass-mf753cdw-wireless-color-laser-printer"
  },
  {
    "id": "PV-010",
    "numericId": 10,
    "sku": "PV-010",
    "name": "Canon MAXIFY GX1020 Wireless Color Inkjet Printer, All-In-One Supertank",
    "category": "Inkjet Printers",
    "brand": "Canon",
    "price": 354.99,
    "oldPrice": 359.99,
    "regularPrice": 359.99,
    "salePrice": 354.99,
    "discount": 1,
    "rating": "4.5",
    "reviews": 115,
    "badge": "Ink Tank",
    "stock": true,
    "printTech": "Color MegaTank Inkjet",
    "type": "printer",
    "svgAccent": "#E30613",
    "image": "images/products/canon-pixma-megatank-g6020.png",
    "description": "High-volume Supertank printer featuring refillable ink tanks that deliver extremely low cost per page and sharp business document clarity.",
    "features": [
      "High-yield refillable MegaTank system",
      "Print speeds up to 15 ipm black / 10 ipm color",
      "250-sheet front paper cassette",
      "2.7-inch color LCD touchscreen"
    ],
    "specifications": {
      "Print Technology": "Color MegaTank Inkjet",
      "Functions": "Print, Copy, Scan",
      "Brand": "Canon",
      "Category": "Inkjet Printers",
      "Connectivity": "Wireless (Wi-Fi), USB 2.0, Mobile App Support",
      "Duplex Printing": "Manual",
      "Paper Handling": "250-sheet front paper cassette"
    },
    "slug": "canon-maxify-gx1020-wireless-color-inkjet-printer-all-in-one-supertank"
  },
  {
    "id": "PV-011",
    "numericId": 11,
    "sku": "PV-011",
    "name": "Canon PIXMA MegaTank G3270 BK Wireless Color Inkjet Printer, All-In-One Supertank",
    "category": "Inkjet Printers",
    "brand": "Canon",
    "price": 249.98,
    "oldPrice": 269.98,
    "regularPrice": 269.98,
    "salePrice": 249.98,
    "discount": 7,
    "rating": "4.6",
    "reviews": 122,
    "badge": "Ink Tank",
    "stock": true,
    "printTech": "Color MegaTank Inkjet",
    "type": "printer",
    "svgAccent": "#E30613",
    "image": "images/products/canon-pixma-megatank-g6020.png",
    "description": "Easy-to-use MegaTank all-in-one printer offering huge ink savings, high page yields up to 6,000 black / 7,700 color pages, and wireless smartphone printing.",
    "features": [
      "Massive ink savings with integrated tanks",
      "1.35-inch square LCD screen",
      "Borderless photo printing up to 8.5x11 inches",
      "Keyed nozzle ink bottles for clean refill"
    ],
    "specifications": {
      "Print Technology": "Color MegaTank Inkjet",
      "Functions": "Print, Copy, Scan",
      "Brand": "Canon",
      "Category": "Inkjet Printers",
      "Connectivity": "Wireless (Wi-Fi), USB 2.0, Mobile App Support",
      "Duplex Printing": "Manual",
      "Paper Handling": "Standard Input Tray"
    },
    "slug": "canon-pixma-megatank-g3270-bk-wireless-color-inkjet-printer-all-in-one-supertank"
  },
  {
    "id": "PV-012",
    "numericId": 12,
    "sku": "PV-012",
    "name": "Canon PIXMA MegaTank G6020 Wireless Color Inkjet Printer, All-In-One Supertank",
    "category": "Inkjet Printers",
    "brand": "Canon",
    "price": 239.99,
    "oldPrice": 319.98,
    "regularPrice": 319.98,
    "salePrice": 239.99,
    "discount": 25,
    "rating": "4.7",
    "reviews": 129,
    "badge": "Special Deal",
    "stock": true,
    "printTech": "Color MegaTank Inkjet",
    "type": "printer",
    "svgAccent": "#E30613",
    "image": "images/products/canon-pixma-megatank-g6020.png",
    "description": "Multi-function MegaTank printer with 350-sheet plain paper capacity, auto 2-sided printing, and voice-activated assistant printing support.",
    "features": [
      "350-sheet total plain paper capacity",
      "Auto 2-sided duplex printing",
      "Wireless & Ethernet network capability",
      "High yield up to 6,000 black pages per bottle set"
    ],
    "specifications": {
      "Print Technology": "Color MegaTank Inkjet",
      "Functions": "Print, Copy, Scan",
      "Brand": "Canon",
      "Category": "Inkjet Printers",
      "Connectivity": "Wireless (Wi-Fi), USB 2.0, Mobile App Support",
      "Duplex Printing": "Automatic 2-Sided",
      "Paper Handling": "350-sheet total plain paper capacity"
    },
    "slug": "canon-pixma-megatank-g6020-wireless-color-inkjet-printer-all-in-one-supertank"
  },
  {
    "id": "PV-013",
    "numericId": 13,
    "sku": "PV-013",
    "name": "Canon PIXMA TR4720 Wireless Color Inkjet Printer, All-In-One",
    "category": "Inkjet Printers",
    "brand": "Canon",
    "price": 109.99,
    "oldPrice": 199.99,
    "regularPrice": 199.99,
    "salePrice": 109.99,
    "discount": 45,
    "rating": "4.8",
    "reviews": 136,
    "badge": "Special Deal",
    "stock": true,
    "printTech": "Color Inkjet",
    "type": "printer",
    "svgAccent": "#E30613",
    "image": "images/products/canon-pixma-megatank-g6020.png",
    "description": "Compact wireless all-in-one printer with 20-sheet ADF, auto 2-sided printing, and intuitive setup via the Canon PRINT app.",
    "features": [
      "All-in-One: Print, Copy, Scan, Fax",
      "Auto 2-sided document printing",
      "20-sheet Auto Document Feeder",
      "Easy setup with Canon PRINT app"
    ],
    "specifications": {
      "Print Technology": "Color Inkjet",
      "Functions": "Print, Copy, Scan, Fax",
      "Brand": "Canon",
      "Category": "Inkjet Printers",
      "Connectivity": "Wireless (Wi-Fi), USB 2.0, Mobile App Support",
      "Duplex Printing": "Automatic 2-Sided",
      "Paper Handling": "20-sheet Auto Document Feeder"
    },
    "slug": "canon-pixma-tr4720-wireless-color-inkjet-printer-all-in-one"
  },
  {
    "id": "PV-014",
    "numericId": 14,
    "sku": "PV-014",
    "name": "Canon PIXMA TR8620a Wireless Color Inkjet Printer, All-In-One",
    "category": "Inkjet Printers",
    "brand": "Canon",
    "price": 199.98,
    "oldPrice": 219.99,
    "regularPrice": 219.99,
    "salePrice": 199.98,
    "discount": 9,
    "rating": "4.9",
    "reviews": 143,
    "badge": "Ink Tank",
    "stock": true,
    "printTech": "Color Inkjet",
    "type": "printer",
    "svgAccent": "#E30613",
    "image": "images/products/canon-pixma-megatank-g6020.png",
    "description": "Home office all-in-one printer featuring a 4.3-inch LCD touchscreen, front/rear paper feeding, memory card slot, and 20-sheet ADF.",
    "features": [
      "4.3-inch intuitive LCD touchscreen",
      "Dual paper feeding (front & rear trays)",
      "Auto 2-sided printing & 20-sheet ADF",
      "Built-in SD memory card slot"
    ],
    "specifications": {
      "Print Technology": "Color Inkjet",
      "Functions": "Print, Copy, Scan, Fax",
      "Brand": "Canon",
      "Category": "Inkjet Printers",
      "Connectivity": "Wireless (Wi-Fi), USB 2.0, Mobile App Support",
      "Duplex Printing": "Automatic 2-Sided",
      "Paper Handling": "Dual paper feeding (front & rear trays)"
    },
    "slug": "canon-pixma-tr8620a-wireless-color-inkjet-printer-all-in-one"
  },
  {
    "id": "PV-015",
    "numericId": 15,
    "sku": "PV-015",
    "name": "Canon PIXMA TS7720 Wireless Color Inkjet Printer, All-In-One",
    "category": "Inkjet Printers",
    "brand": "Canon",
    "price": 124.99,
    "oldPrice": 161.99,
    "regularPrice": 161.99,
    "salePrice": 124.99,
    "discount": 23,
    "rating": "4.5",
    "reviews": 150,
    "badge": "Special Deal",
    "stock": true,
    "printTech": "Color Inkjet",
    "type": "printer",
    "svgAccent": "#E30613",
    "image": "images/products/canon-pixma-megatank-g6020.png",
    "description": "Sleek and efficient wireless printer engineered for fast document printing, clear photo output, and smooth UI touchscreen navigation.",
    "features": [
      "Fast print speeds: 15 ipm black / 10 ipm color",
      "2.7-inch color touchscreen",
      "Switchable dual paper tray input",
      "Wireless 2.4GHz & 5GHz dual-band support"
    ],
    "specifications": {
      "Print Technology": "Color Inkjet",
      "Functions": "Print, Copy, Scan",
      "Brand": "Canon",
      "Category": "Inkjet Printers",
      "Connectivity": "Wireless (Wi-Fi), USB 2.0, Mobile App Support",
      "Duplex Printing": "Manual",
      "Paper Handling": "Switchable dual paper tray input"
    },
    "slug": "canon-pixma-ts7720-wireless-color-inkjet-printer-all-in-one"
  },
  {
    "id": "PV-016",
    "numericId": 16,
    "sku": "PV-016",
    "name": "Canon PIXMA TS3520 Wireless Color All-In-One Inkjet Printer",
    "category": "Inkjet Printers",
    "brand": "Canon",
    "price": 79.99,
    "oldPrice": 99.99,
    "regularPrice": 99.99,
    "salePrice": 79.99,
    "discount": 20,
    "rating": "4.6",
    "reviews": 157,
    "badge": "Special Deal",
    "stock": true,
    "printTech": "Color Inkjet",
    "type": "printer",
    "svgAccent": "#E30613",
    "image": "images/products/canon-pixma-megatank-g6020.png",
    "description": "Simple, easy-to-use wireless all-in-one printer designed for everyday basic document and photo printing.",
    "features": [
      "1.5-inch segment LCD screen",
      "Wireless Connect simple button setup",
      "Rear paper tray for quick media loading",
      "FINE hybrid ink system"
    ],
    "specifications": {
      "Print Technology": "Color Inkjet",
      "Functions": "Print, Copy, Scan",
      "Brand": "Canon",
      "Category": "Inkjet Printers",
      "Connectivity": "Wireless (Wi-Fi), USB 2.0, Mobile App Support",
      "Duplex Printing": "Manual",
      "Paper Handling": "Rear paper tray for quick media loading"
    },
    "slug": "canon-pixma-ts3520-wireless-color-all-in-one-inkjet-printer"
  },
  {
    "id": "PV-017",
    "numericId": 17,
    "sku": "PV-017",
    "name": "Epson EcoTank ET-2800 Wireless Color Inkjet Printer, All-In-One Supertank",
    "category": "Inkjet Printers",
    "brand": "Epson",
    "price": 239.99,
    "oldPrice": 249.99,
    "regularPrice": 249.99,
    "salePrice": 239.99,
    "discount": 4,
    "rating": "4.7",
    "reviews": 164,
    "badge": "Ink Tank",
    "stock": true,
    "printTech": "Cartridge-Free EcoTank",
    "type": "printer",
    "svgAccent": "#0284C7",
    "image": "images/products/canon-pixma-megatank-g6020.png",
    "description": "Innovative cartridge-free Supertank printer using high-capacity refillable ink tanks. Includes up to 2 years of ink in the box for low-cost printing.",
    "features": [
      "Cartridge-free printing with high-capacity tanks",
      "Up to 2 years of ink included in box",
      "MicroPiezo Heat-Free technology",
      "High-resolution flatbed scanner"
    ],
    "specifications": {
      "Print Technology": "Cartridge-Free EcoTank",
      "Functions": "Print, Copy, Scan",
      "Brand": "Epson",
      "Category": "Inkjet Printers",
      "Connectivity": "Wireless (Wi-Fi), USB 2.0, Mobile App Support",
      "Duplex Printing": "Manual",
      "Paper Handling": "Standard Input Tray"
    },
    "slug": "epson-ecotank-et-2800-wireless-color-inkjet-printer-all-in-one-supertank"
  },
  {
    "id": "PV-018",
    "numericId": 18,
    "sku": "PV-018",
    "name": "Epson EcoTank ET-2980 Wireless All-in-One Color Supertank Printer",
    "category": "Inkjet Printers",
    "brand": "Epson",
    "price": 299.99,
    "oldPrice": 329.99,
    "regularPrice": 329.99,
    "salePrice": 299.99,
    "discount": 9,
    "rating": "4.8",
    "reviews": 171,
    "badge": "Ink Tank",
    "stock": true,
    "printTech": "Cartridge-Free EcoTank",
    "type": "printer",
    "svgAccent": "#0284C7",
    "image": "images/products/canon-pixma-megatank-g6020.png",
    "description": "Modern color Supertank printer with auto 2-sided printing, color display, and hands-free voice-activated printing capability.",
    "features": [
      "Automatic 2-sided duplex printing",
      "Color LCD screen navigation",
      "Hands-free voice-activated printing",
      "Stress-free refill with EcoFit bottles"
    ],
    "specifications": {
      "Print Technology": "Cartridge-Free EcoTank",
      "Functions": "Print, Copy, Scan",
      "Brand": "Epson",
      "Category": "Inkjet Printers",
      "Connectivity": "Wireless (Wi-Fi), USB 2.0, Mobile App Support",
      "Duplex Printing": "Automatic 2-Sided",
      "Paper Handling": "Standard Input Tray"
    },
    "slug": "epson-ecotank-et-2980-wireless-all-in-one-color-supertank-printer"
  },
  {
    "id": "PV-019",
    "numericId": 19,
    "sku": "PV-019",
    "name": "Epson EcoTank ET-3950 Wireless All-in-One Color Supertank Printer – White",
    "category": "Inkjet Printers",
    "brand": "Epson",
    "price": 419.99,
    "oldPrice": 439.99,
    "regularPrice": 439.99,
    "salePrice": 419.99,
    "discount": 5,
    "rating": "4.9",
    "reviews": 178,
    "badge": "Ink Tank",
    "stock": true,
    "printTech": "PrecisionCore EcoTank",
    "type": "printer",
    "svgAccent": "#0284C7",
    "image": "images/products/canon-pixma-megatank-g6020.png",
    "description": "Premium white EcoTank printer powered by PrecisionCore Heat-Free technology. Offers 250-sheet paper capacity, auto 2-sided printing, and ADF.",
    "features": [
      "PrecisionCore Heat-Free technology",
      "250-sheet paper tray capacity",
      "30-sheet auto document feeder",
      "2.4-inch color touchscreen"
    ],
    "specifications": {
      "Print Technology": "PrecisionCore EcoTank",
      "Functions": "Print, Copy, Scan",
      "Brand": "Epson",
      "Category": "Inkjet Printers",
      "Connectivity": "Wireless (Wi-Fi), USB 2.0, Mobile App Support",
      "Duplex Printing": "Manual",
      "Paper Handling": "250-sheet paper tray capacity"
    },
    "slug": "epson-ecotank-et-3950-wireless-all-in-one-color-supertank-printer-white"
  },
  {
    "id": "PV-020",
    "numericId": 20,
    "sku": "PV-020",
    "name": "Epson EcoTank ET-4950 Wireless All-in-One Color Supertank Printer",
    "category": "Inkjet Printers",
    "brand": "Epson",
    "price": 494.98,
    "oldPrice": 499.99,
    "regularPrice": 499.99,
    "salePrice": 494.98,
    "discount": 1,
    "rating": "4.5",
    "reviews": 185,
    "badge": "Ink Tank",
    "stock": true,
    "printTech": "PrecisionCore EcoTank",
    "type": "printer",
    "svgAccent": "#0284C7",
    "image": "images/products/canon-pixma-megatank-g6020.png",
    "description": "Heavy-duty business Supertank printer with fax, Ethernet, auto 2-sided scanning/printing, and high-yield ink capacity.",
    "features": [
      "Auto 2-sided printing & 30-sheet ADF",
      "Built-in Ethernet & Wi-Fi Direct",
      "Low cost per print page",
      "2.4-inch color LCD touch display"
    ],
    "specifications": {
      "Print Technology": "PrecisionCore EcoTank",
      "Functions": "Print, Copy, Scan, Fax",
      "Brand": "Epson",
      "Category": "Inkjet Printers",
      "Connectivity": "Wireless (Wi-Fi), USB 2.0, Mobile App Support",
      "Duplex Printing": "Automatic 2-Sided",
      "Paper Handling": "Auto 2-sided printing & 30-sheet ADF"
    },
    "slug": "epson-ecotank-et-4950-wireless-all-in-one-color-supertank-printer"
  },
  {
    "id": "PV-021",
    "numericId": 21,
    "sku": "PV-021",
    "name": "Epson EcoTank Photo ET-8550 Wireless Color Inkjet Printer, Wide Format",
    "category": "Inkjet Printers",
    "brand": "Epson",
    "price": 739.98,
    "oldPrice": 749.99,
    "regularPrice": 749.99,
    "salePrice": 739.98,
    "discount": 1,
    "rating": "4.6",
    "reviews": 192,
    "badge": "Ink Tank",
    "stock": true,
    "printTech": "6-Color Claria ET Premium",
    "type": "printer",
    "svgAccent": "#0284C7",
    "image": "images/build.png",
    "description": "Versatile wide-format photo Supertank printer capable of printing borderless photos up to 13x19 inches with 6-color pigment & dye inks.",
    "features": [
      "Wide-format borderless photo printing up to 13x19\"",
      "6-color Claria ET Premium ink system",
      "4.3-inch color touchscreen",
      "Custom media handling including cardstock & CD/DVD"
    ],
    "specifications": {
      "Print Technology": "6-Color Claria ET Premium",
      "Functions": "Print, Copy, Scan",
      "Brand": "Epson",
      "Category": "Inkjet Printers",
      "Connectivity": "Wireless (Wi-Fi), USB 2.0, Mobile App Support",
      "Duplex Printing": "Manual",
      "Paper Handling": "Standard Input Tray"
    },
    "slug": "epson-ecotank-photo-et-8550-wireless-color-inkjet-printer-wide-format"
  },
  {
    "id": "PV-022",
    "numericId": 22,
    "sku": "PV-022",
    "name": "Epson Expression Home XP-4200 Wireless Color Inkjet Printer",
    "category": "Inkjet Printers",
    "brand": "Epson",
    "price": 79.99,
    "oldPrice": 99.99,
    "regularPrice": 99.99,
    "salePrice": 79.99,
    "discount": 20,
    "rating": "4.7",
    "reviews": 49,
    "badge": "Special Deal",
    "stock": true,
    "printTech": "Color Inkjet",
    "type": "printer",
    "svgAccent": "#0284C7",
    "image": "images/build.png",
    "description": "Compact wireless all-in-one printer with 2.4-inch color LCD, auto 2-sided printing, and instant hands-free voice printing.",
    "features": [
      "Auto 2-sided printing",
      "2.4-inch color LCD display",
      "Individual 4-color ink cartridges",
      "Epson Smart Panel app setup"
    ],
    "specifications": {
      "Print Technology": "Color Inkjet",
      "Functions": "Print, Copy, Scan",
      "Brand": "Epson",
      "Category": "Inkjet Printers",
      "Connectivity": "Wireless (Wi-Fi), USB 2.0, Mobile App Support",
      "Duplex Printing": "Automatic 2-Sided",
      "Paper Handling": "Standard Input Tray"
    },
    "slug": "epson-expression-home-xp-4200-wireless-color-inkjet-printer"
  },
  {
    "id": "PV-023",
    "numericId": 23,
    "sku": "PV-023",
    "name": "Epson Expression Premium XP-7100 Wireless Color Inkjet Printer",
    "category": "Inkjet Printers",
    "brand": "Epson",
    "price": 169.99,
    "oldPrice": 249.99,
    "regularPrice": 249.99,
    "salePrice": 169.99,
    "discount": 32,
    "rating": "4.8",
    "reviews": 56,
    "badge": "Special Deal",
    "stock": true,
    "printTech": "5-Color Inkjet",
    "type": "printer",
    "svgAccent": "#0284C7",
    "image": "images/build.png",
    "description": "Premium photo all-in-one printer with 30-sheet auto document feeder, 4.3-inch touchscreen, and dedicated photo paper tray.",
    "features": [
      "5-color ink set for vivid photos & sharp text",
      "Auto 2-sided 30-sheet document feeder",
      "4.3-inch intuitive touchscreen",
      "Direct photo printing from USB & SD cards"
    ],
    "specifications": {
      "Print Technology": "5-Color Inkjet",
      "Functions": "Print, Copy, Scan, Fax",
      "Brand": "Epson",
      "Category": "Inkjet Printers",
      "Connectivity": "Wireless (Wi-Fi), USB 2.0, Mobile App Support",
      "Duplex Printing": "Automatic 2-Sided",
      "Paper Handling": "Auto 2-sided 30-sheet document feeder"
    },
    "slug": "epson-expression-premium-xp-7100-wireless-color-inkjet-printer"
  },
  {
    "id": "PV-024",
    "numericId": 24,
    "sku": "PV-024",
    "name": "Epson WorkForce Pro WF-3820 Wireless Color Inkjet Printer",
    "category": "Inkjet Printers",
    "brand": "Epson",
    "price": 139.99,
    "oldPrice": 199.99,
    "regularPrice": 199.99,
    "salePrice": 139.99,
    "discount": 30,
    "rating": "4.9",
    "reviews": 63,
    "badge": "Special Deal",
    "stock": true,
    "printTech": "PrecisionCore Inkjet",
    "type": "printer",
    "svgAccent": "#0284C7",
    "image": "images/build.png",
    "description": "High-speed business inkjet printer engineered for heavy workloads with PrecisionCore technology, 250-sheet tray, and 2.7-inch touchscreen.",
    "features": [
      "Print speeds: 21 black / 11 color ppm",
      "250-sheet paper capacity cassette",
      "2.7-inch color touchscreen",
      "DURABrite Ultra instant-dry pigment inks"
    ],
    "specifications": {
      "Print Technology": "PrecisionCore Inkjet",
      "Functions": "Print, Copy, Scan, Fax",
      "Brand": "Epson",
      "Category": "Inkjet Printers",
      "Connectivity": "Wireless (Wi-Fi), USB 2.0, Mobile App Support",
      "Duplex Printing": "Manual",
      "Paper Handling": "250-sheet paper capacity cassette"
    },
    "slug": "epson-workforce-pro-wf-3820-wireless-color-inkjet-printer"
  },
  {
    "id": "PV-025",
    "numericId": 25,
    "sku": "PV-025",
    "name": "Epson EcoTank ET-2850 Wireless Color All-in-One Cartridge-Free Supertank Printer",
    "category": "Inkjet Printers",
    "brand": "Epson",
    "price": 279.99,
    "oldPrice": 299.99,
    "regularPrice": 299.99,
    "salePrice": 279.99,
    "discount": 7,
    "rating": "4.5",
    "reviews": 70,
    "badge": "Ink Tank",
    "stock": true,
    "printTech": "Cartridge-Free EcoTank",
    "type": "printer",
    "svgAccent": "#0284C7",
    "image": "images/products/canon-pixma-megatank-g6020.png",
    "description": "Efficient Supertank printer featuring automatic two-sided printing, high-resolution flatbed scanner, and EcoFit bottle system.",
    "features": [
      "Auto 2-sided duplex printing",
      "High-yield replacement ink bottles",
      "MicroPiezo Heat-Free Technology",
      "Easy wireless connection with Wi-Fi Direct"
    ],
    "specifications": {
      "Print Technology": "Cartridge-Free EcoTank",
      "Functions": "Print, Copy, Scan",
      "Brand": "Epson",
      "Category": "Inkjet Printers",
      "Connectivity": "Wireless (Wi-Fi), USB 2.0, Mobile App Support",
      "Duplex Printing": "Automatic 2-Sided",
      "Paper Handling": "Standard Input Tray"
    },
    "slug": "epson-ecotank-et-2850-wireless-color-all-in-one-cartridge-free-supertank-printer"
  },
  {
    "id": "PV-026",
    "numericId": 26,
    "sku": "PV-026",
    "name": "HP DeskJet 2855e Wireless Color All-in-One Printer, Scan, Copy",
    "category": "Inkjet Printers",
    "brand": "HP",
    "price": 69.99,
    "oldPrice": 89.99,
    "regularPrice": 89.99,
    "salePrice": 69.99,
    "discount": 22,
    "rating": "4.6",
    "reviews": 77,
    "badge": "Special Deal",
    "stock": true,
    "printTech": "Color Inkjet",
    "type": "printer",
    "svgAccent": "#059669",
    "image": "images/build.png",
    "description": "Compact wireless color all-in-one printer for essential home document printing with HP app mobile printing.",
    "features": [
      "Print, copy, and scan capabilities",
      "Self-healing Wi-Fi connection",
      "Compact lightweight design",
      "Easy setup with HP Smart app"
    ],
    "specifications": {
      "Print Technology": "Color Inkjet",
      "Functions": "Print, Copy, Scan",
      "Brand": "HP",
      "Category": "Inkjet Printers",
      "Connectivity": "Wireless (Wi-Fi), USB 2.0, Mobile App Support",
      "Duplex Printing": "Manual",
      "Paper Handling": "Standard Input Tray"
    },
    "slug": "hp-deskjet-2855e-wireless-color-all-in-one-printer-scan-copy"
  },
  {
    "id": "PV-027",
    "numericId": 27,
    "sku": "PV-027",
    "name": "HP DeskJet 4255e Wireless Color All-in-One Printer, Scan, Copy",
    "category": "Inkjet Printers",
    "brand": "HP",
    "price": 89.99,
    "oldPrice": 109.99,
    "regularPrice": 109.99,
    "salePrice": 89.99,
    "discount": 18,
    "rating": "4.7",
    "reviews": 84,
    "badge": "Special Deal",
    "stock": true,
    "printTech": "Color Inkjet",
    "type": "printer",
    "svgAccent": "#059669",
    "image": "images/build.png",
    "description": "Upgraded DeskJet printer featuring a 35-sheet auto document feeder for multi-page copying and scanning convenience.",
    "features": [
      "35-sheet automatic document feeder",
      "Wireless printing & mobile scanning",
      "Print speeds up to 8.5 ppm black / 5.5 ppm color",
      "60-sheet input tray capacity"
    ],
    "specifications": {
      "Print Technology": "Color Inkjet",
      "Functions": "Print, Copy, Scan",
      "Brand": "HP",
      "Category": "Inkjet Printers",
      "Connectivity": "Wireless (Wi-Fi), USB 2.0, Mobile App Support",
      "Duplex Printing": "Manual",
      "Paper Handling": "35-sheet automatic document feeder"
    },
    "slug": "hp-deskjet-4255e-wireless-color-all-in-one-printer-scan-copy"
  },
  {
    "id": "PV-028",
    "numericId": 28,
    "sku": "PV-028",
    "name": "HP Envy 6155e Wireless Color All-in-One Printer, Scan, Copy",
    "category": "Inkjet Printers",
    "brand": "HP",
    "price": 139.99,
    "oldPrice": 159.99,
    "regularPrice": 159.99,
    "salePrice": 139.99,
    "discount": 13,
    "rating": "4.8",
    "reviews": 91,
    "badge": "Ink Tank",
    "stock": true,
    "printTech": "Color Inkjet",
    "type": "printer",
    "svgAccent": "#059669",
    "image": "images/build.png",
    "description": "Stylish home printer designed for borderless photo printing, auto 2-sided document printing, and quiet mode operation.",
    "features": [
      "Automatic 2-sided duplex printing",
      "Borderless photo printing up to 8.5x11\"",
      "Dual-band self-healing Wi-Fi",
      "Contextual touchscreen control panel"
    ],
    "specifications": {
      "Print Technology": "Color Inkjet",
      "Functions": "Print, Copy, Scan",
      "Brand": "HP",
      "Category": "Inkjet Printers",
      "Connectivity": "Wireless (Wi-Fi), USB 2.0, Mobile App Support",
      "Duplex Printing": "Automatic 2-Sided",
      "Paper Handling": "Standard Input Tray"
    },
    "slug": "hp-envy-6155e-wireless-color-all-in-one-printer-scan-copy"
  },
  {
    "id": "PV-029",
    "numericId": 29,
    "sku": "PV-029",
    "name": "HP Envy 6555e Wireless Color All-in-One Printer, Scan, Copy",
    "category": "Inkjet Printers",
    "brand": "HP",
    "price": 179.99,
    "oldPrice": 199.99,
    "regularPrice": 199.99,
    "salePrice": 179.99,
    "discount": 10,
    "rating": "4.9",
    "reviews": 98,
    "badge": "Ink Tank",
    "stock": true,
    "printTech": "Color Inkjet",
    "type": "printer",
    "svgAccent": "#059669",
    "image": "images/build.png",
    "description": "Advanced Envy home printer with dedicated photo tray, auto 2-sided printing, and vibrant true-to-life photo color output.",
    "features": [
      "Built-in photo tray for 4x6 photo paper",
      "Auto 2-sided printing",
      "High resolution 4800 x 1200 dpi",
      "2.4-inch color touchscreen display"
    ],
    "specifications": {
      "Print Technology": "Color Inkjet",
      "Functions": "Print, Copy, Scan",
      "Brand": "HP",
      "Category": "Inkjet Printers",
      "Connectivity": "Wireless (Wi-Fi), USB 2.0, Mobile App Support",
      "Duplex Printing": "Automatic 2-Sided",
      "Paper Handling": "Built-in photo tray for 4x6 photo paper"
    },
    "slug": "hp-envy-6555e-wireless-color-all-in-one-printer-scan-copy"
  },
  {
    "id": "PV-030",
    "numericId": 30,
    "sku": "PV-030",
    "name": "HP Envy Inspire 7255e Wireless Color All-in-One Printer, Scan, Copy",
    "category": "Inkjet Printers",
    "brand": "HP",
    "price": 159.99,
    "oldPrice": 209.99,
    "regularPrice": 209.99,
    "salePrice": 159.99,
    "discount": 24,
    "rating": "4.5",
    "reviews": 105,
    "badge": "Special Deal",
    "stock": true,
    "printTech": "Color Inkjet",
    "type": "printer",
    "svgAccent": "#059669",
    "image": "images/build.png",
    "description": "Versatile family printer featuring custom photo features, square and 2-sided photo printing, and dual-band Wi-Fi connection.",
    "features": [
      "Built-in photo tray & 2-sided photo printing",
      "Custom templates via HP Smart app",
      "Print speeds up to 15 ppm black / 10 ppm color",
      "Quiet printing mode for home environments"
    ],
    "specifications": {
      "Print Technology": "Color Inkjet",
      "Functions": "Print, Copy, Scan",
      "Brand": "HP",
      "Category": "Inkjet Printers",
      "Connectivity": "Wireless (Wi-Fi), USB 2.0, Mobile App Support",
      "Duplex Printing": "Automatic 2-Sided",
      "Paper Handling": "Built-in photo tray & 2-sided photo printing"
    },
    "slug": "hp-envy-inspire-7255e-wireless-color-all-in-one-printer-scan-copy"
  },
  {
    "id": "PV-031",
    "numericId": 31,
    "sku": "PV-031",
    "name": "HP LaserJet MFP M140w Wireless Black & White All-in-One Laser Printer",
    "category": "Laser Printers",
    "brand": "HP",
    "price": 539.99,
    "oldPrice": 569.99,
    "regularPrice": 569.99,
    "salePrice": 539.99,
    "discount": 5,
    "rating": "4.6",
    "reviews": 112,
    "badge": "Laser Pro",
    "stock": true,
    "printTech": "Monochrome Laser",
    "type": "printer",
    "svgAccent": "#059669",
    "image": "images/build.png",
    "description": "Ultra-compact wireless black and white laser all-in-one printer. Perfect for tight office spaces needing fast laser quality printing and copying.",
    "features": [
      "World's smallest laser printer in its class",
      "Print speeds up to 21 ppm",
      "Wireless & Wi-Fi Direct printing",
      "High quality flatbed scanner"
    ],
    "specifications": {
      "Print Technology": "Monochrome Laser",
      "Functions": "Print, Copy, Scan",
      "Brand": "HP",
      "Category": "Laser Printers",
      "Connectivity": "Wireless (Wi-Fi), USB 2.0, Mobile App Support",
      "Duplex Printing": "Manual",
      "Paper Handling": "Standard Input Tray"
    },
    "slug": "hp-laserjet-mfp-m140w-wireless-black-white-all-in-one-laser-printer"
  },
  {
    "id": "PV-032",
    "numericId": 32,
    "sku": "PV-032",
    "name": "HP LaserJet Pro 3001dw Wireless Black & White Laser Printer",
    "category": "Laser Printers",
    "brand": "HP",
    "price": 199.99,
    "oldPrice": 249.99,
    "regularPrice": 249.99,
    "salePrice": 199.99,
    "discount": 20,
    "rating": "4.7",
    "reviews": 119,
    "badge": "Special Deal",
    "stock": true,
    "printTech": "Monochrome Laser",
    "type": "printer",
    "svgAccent": "#059669",
    "image": "images/build.png",
    "description": "Business-class monochrome laser printer built for speed, robust security management, and dual-sided high-speed printing.",
    "features": [
      "Fast print speeds up to 35 ppm",
      "Automatic 2-sided duplex printing",
      "Dual-band Wi-Fi with self-healing",
      "HP Wolf Pro security management"
    ],
    "specifications": {
      "Print Technology": "Monochrome Laser",
      "Functions": "Print Only",
      "Brand": "HP",
      "Category": "Laser Printers",
      "Connectivity": "Wireless (Wi-Fi), USB 2.0, Mobile App Support",
      "Duplex Printing": "Automatic 2-Sided",
      "Paper Handling": "Standard Input Tray"
    },
    "slug": "hp-laserjet-pro-3001dw-wireless-black-white-laser-printer"
  },
  {
    "id": "PV-033",
    "numericId": 33,
    "sku": "PV-033",
    "name": "HP LaserJet Pro 3201dw Wireless Color Laser Printer",
    "category": "Laser Printers",
    "brand": "HP",
    "price": 399.99,
    "oldPrice": 429.99,
    "regularPrice": 429.99,
    "salePrice": 399.99,
    "discount": 7,
    "rating": "4.8",
    "reviews": 126,
    "badge": "Laser Pro",
    "stock": true,
    "printTech": "Color Laser",
    "type": "printer",
    "svgAccent": "#059669",
    "image": "images/build.png",
    "description": "Compact wireless color laser printer delivering sharp text and vivid color business graphics for small workgroups.",
    "features": [
      "Print speeds up to 26 ppm color & black",
      "Auto 2-sided printing",
      "250-sheet input paper tray",
      "HP Wolf Pro security embedded"
    ],
    "specifications": {
      "Print Technology": "Color Laser",
      "Functions": "Print Only",
      "Brand": "HP",
      "Category": "Laser Printers",
      "Connectivity": "Wireless (Wi-Fi), USB 2.0, Mobile App Support",
      "Duplex Printing": "Automatic 2-Sided",
      "Paper Handling": "250-sheet input paper tray"
    },
    "slug": "hp-laserjet-pro-3201dw-wireless-color-laser-printer"
  },
  {
    "id": "PV-034",
    "numericId": 34,
    "sku": "PV-034",
    "name": "HP LaserJet Pro LJP 4201dn Color Laser Printer",
    "category": "Laser Printers",
    "brand": "HP",
    "price": 549.99,
    "oldPrice": 669.99,
    "regularPrice": 669.99,
    "salePrice": 549.99,
    "discount": 18,
    "rating": "4.9",
    "reviews": 133,
    "badge": "Special Deal",
    "stock": true,
    "printTech": "Color Laser",
    "type": "printer",
    "svgAccent": "#059669",
    "image": "images/build.png",
    "description": "High-performance enterprise color laser printer designed for demanding offices with heavy monthly printing requirements.",
    "features": [
      "Blazing speeds up to 35 ppm color & black",
      "Gigabit Ethernet networking",
      "50-sheet multipurpose tray + 250-sheet input tray",
      "Dynamic security & encrypted print output"
    ],
    "specifications": {
      "Print Technology": "Color Laser",
      "Functions": "Print Only",
      "Brand": "HP",
      "Category": "Laser Printers",
      "Connectivity": "Wireless (Wi-Fi), USB 2.0, Mobile App Support",
      "Duplex Printing": "Manual",
      "Paper Handling": "50-sheet multipurpose tray + 250-sheet input tray"
    },
    "slug": "hp-laserjet-pro-ljp-4201dn-color-laser-printer"
  },
  {
    "id": "PV-035",
    "numericId": 35,
    "sku": "PV-035",
    "name": "HP LaserJet Pro MFP 4301fdw Wireless Color All-In-One Laser Printer",
    "category": "Laser Printers",
    "brand": "HP",
    "price": 869.99,
    "oldPrice": 899.99,
    "regularPrice": 899.99,
    "salePrice": 869.99,
    "discount": 3,
    "rating": "4.5",
    "reviews": 140,
    "badge": "Laser Pro",
    "stock": true,
    "printTech": "Color Laser",
    "type": "printer",
    "svgAccent": "#059669",
    "image": "images/build.png",
    "description": "Flagship commercial color laser all-in-one printer featuring 35 ppm print speed, 4.3-inch touchscreen, and single-pass duplex scanning.",
    "features": [
      "Print, Copy, Scan, Fax all-in-one functionality",
      "Fast 35 ppm print & copy speed",
      "Single-pass 2-sided auto document feeder",
      "4.3-inch customizable color touchscreen"
    ],
    "specifications": {
      "Print Technology": "Color Laser",
      "Functions": "Print, Copy, Scan, Fax",
      "Brand": "HP",
      "Category": "Laser Printers",
      "Connectivity": "Wireless (Wi-Fi), USB 2.0, Mobile App Support",
      "Duplex Printing": "Automatic 2-Sided",
      "Paper Handling": "Standard Input Tray"
    },
    "slug": "hp-laserjet-pro-mfp-4301fdw-wireless-color-all-in-one-laser-printer"
  },
  {
    "id": "PV-036",
    "numericId": 36,
    "sku": "PV-036",
    "name": "HP OfficeJet Pro 8125e Wireless Color All-in-One Printer, Scan, Copy",
    "category": "Inkjet Printers",
    "brand": "HP",
    "price": 149.99,
    "oldPrice": 179.99,
    "regularPrice": 179.99,
    "salePrice": 149.99,
    "discount": 17,
    "rating": "4.6",
    "reviews": 147,
    "badge": "Special Deal",
    "stock": true,
    "printTech": "Thermal Inkjet",
    "type": "printer",
    "svgAccent": "#059669",
    "image": "images/build.png",
    "description": "Reliable small office inkjet printer with fast print speeds, auto 2-sided printing, and self-healing Wi-Fi.",
    "features": [
      "Print speeds up to 20 ppm black / 10 ppm color",
      "Auto 2-sided printing",
      "225-sheet input tray capacity",
      "2.7-inch color touchscreen display"
    ],
    "specifications": {
      "Print Technology": "Thermal Inkjet",
      "Functions": "Print, Copy, Scan",
      "Brand": "HP",
      "Category": "Inkjet Printers",
      "Connectivity": "Wireless (Wi-Fi), USB 2.0, Mobile App Support",
      "Duplex Printing": "Automatic 2-Sided",
      "Paper Handling": "225-sheet input tray capacity"
    },
    "slug": "hp-officejet-pro-8125e-wireless-color-all-in-one-printer-scan-copy"
  },
  {
    "id": "PV-037",
    "numericId": 37,
    "sku": "PV-037",
    "name": "HP OfficeJet Pro 8139e Wireless Color All-In-One Printer, Scan, Copy, Fax",
    "category": "Inkjet Printers",
    "brand": "HP",
    "price": 219.99,
    "oldPrice": 279.99,
    "regularPrice": 279.99,
    "salePrice": 219.99,
    "discount": 21,
    "rating": "4.7",
    "reviews": 154,
    "badge": "Special Deal",
    "stock": true,
    "printTech": "Thermal Inkjet",
    "type": "printer",
    "svgAccent": "#059669",
    "image": "images/build.png",
    "description": "Full-featured office printer equipped with fax, 35-sheet document feeder, fast printing, and robust security safeguards.",
    "features": [
      "Print speeds up to 20 ppm black / 10 ppm color",
      "35-sheet automatic document feeder",
      "Fax send/receive functionality",
      "Self-healing dual-band Wi-Fi"
    ],
    "specifications": {
      "Print Technology": "Thermal Inkjet",
      "Functions": "Print, Copy, Scan, Fax",
      "Brand": "HP",
      "Category": "Inkjet Printers",
      "Connectivity": "Wireless (Wi-Fi), USB 2.0, Mobile App Support",
      "Duplex Printing": "Manual",
      "Paper Handling": "35-sheet automatic document feeder"
    },
    "slug": "hp-officejet-pro-8139e-wireless-color-all-in-one-printer-scan-copy-fax"
  },
  {
    "id": "PV-038",
    "numericId": 38,
    "sku": "PV-038",
    "name": "HP OfficeJet Pro 9110b Wireless Color Inkjet Printer",
    "category": "Inkjet Printers",
    "brand": "HP",
    "price": 189.99,
    "oldPrice": 199.99,
    "regularPrice": 199.99,
    "salePrice": 189.99,
    "discount": 5,
    "rating": "4.8",
    "reviews": 161,
    "badge": "Ink Tank",
    "stock": true,
    "printTech": "Thermal Inkjet",
    "type": "printer",
    "svgAccent": "#059669",
    "image": "images/build.png",
    "description": "Dedicated high-volume business color inkjet printer built for fast speed, high paper capacity, and sharp document text.",
    "features": [
      "High speeds up to 22 ppm black / 18 ppm color",
      "250-sheet input tray",
      "Automatic 2-sided printing",
      "USB 2.0, Ethernet & Wi-Fi connectivity"
    ],
    "specifications": {
      "Print Technology": "Thermal Inkjet",
      "Functions": "Print Only",
      "Brand": "HP",
      "Category": "Inkjet Printers",
      "Connectivity": "Wireless (Wi-Fi), USB 2.0, Mobile App Support",
      "Duplex Printing": "Automatic 2-Sided",
      "Paper Handling": "250-sheet input tray"
    },
    "slug": "hp-officejet-pro-9110b-wireless-color-inkjet-printer"
  },
  {
    "id": "PV-039",
    "numericId": 39,
    "sku": "PV-039",
    "name": "HP OfficeJet Pro 9125e Wireless Color All-In-One Printer, Scan, Copy, Fax",
    "category": "Inkjet Printers",
    "brand": "HP",
    "price": 309.99,
    "oldPrice": 339.99,
    "regularPrice": 339.99,
    "salePrice": 309.99,
    "discount": 9,
    "rating": "4.9",
    "reviews": 168,
    "badge": "Ink Tank",
    "stock": true,
    "printTech": "Thermal Inkjet",
    "type": "printer",
    "svgAccent": "#059669",
    "image": "images/build.png",
    "description": "Pro-level business inkjet all-in-one printer featuring 22 ppm speed, 2.7-inch touchscreen, and auto 2-sided scanning.",
    "features": [
      "Print speeds up to 22 ppm black / 18 ppm color",
      "Auto 2-sided scanning & copying",
      "250-sheet input tray capacity",
      "HP Wolf Pro Security built-in"
    ],
    "specifications": {
      "Print Technology": "Thermal Inkjet",
      "Functions": "Print, Copy, Scan, Fax",
      "Brand": "HP",
      "Category": "Inkjet Printers",
      "Connectivity": "Wireless (Wi-Fi), USB 2.0, Mobile App Support",
      "Duplex Printing": "Automatic 2-Sided",
      "Paper Handling": "250-sheet input tray capacity"
    },
    "slug": "hp-officejet-pro-9125e-wireless-color-all-in-one-printer-scan-copy-fax"
  },
  {
    "id": "PV-040",
    "numericId": 40,
    "sku": "PV-040",
    "name": "HP OfficeJet Pro 9135e Wireless Color All-In-One Printer, Scan, Copy, Fax",
    "category": "Inkjet Printers",
    "brand": "HP",
    "price": 369.99,
    "oldPrice": 429.99,
    "regularPrice": 429.99,
    "salePrice": 369.99,
    "discount": 14,
    "rating": "4.5",
    "reviews": 175,
    "badge": "Ink Tank",
    "stock": true,
    "printTech": "Thermal Inkjet",
    "type": "printer",
    "svgAccent": "#059669",
    "image": "images/build.png",
    "description": "Dual-tray office printer holding up to 500 sheets of paper. Designed for heavy daily printing with fast 25 ppm output.",
    "features": [
      "500-sheet dual paper tray capacity",
      "Fast print speeds up to 25 ppm black / 20 ppm color",
      "Single-pass 2-sided auto document feeder",
      "4.3-inch color touchscreen display"
    ],
    "specifications": {
      "Print Technology": "Thermal Inkjet",
      "Functions": "Print, Copy, Scan, Fax",
      "Brand": "HP",
      "Category": "Inkjet Printers",
      "Connectivity": "Wireless (Wi-Fi), USB 2.0, Mobile App Support",
      "Duplex Printing": "Automatic 2-Sided",
      "Paper Handling": "500-sheet dual paper tray capacity"
    },
    "slug": "hp-officejet-pro-9135e-wireless-color-all-in-one-printer-scan-copy-fax"
  },
  {
    "id": "PV-041",
    "numericId": 41,
    "sku": "PV-041",
    "name": "HP OfficeJet Pro 9730e Wide Format Wireless Color All-In-One Printer",
    "category": "Inkjet Printers",
    "brand": "HP",
    "price": 439.99,
    "oldPrice": 449.99,
    "regularPrice": 449.99,
    "salePrice": 439.99,
    "discount": 2,
    "rating": "4.6",
    "reviews": 182,
    "badge": "Ink Tank",
    "stock": true,
    "printTech": "Thermal Inkjet",
    "type": "printer",
    "svgAccent": "#059669",
    "image": "images/build.png",
    "description": "Wide-format business printer capable of printing up to 11x17 inch documents and posters with vibrant color accuracy.",
    "features": [
      "Wide format printing up to 11x17 inches (A3)",
      "Dual 250-sheet paper trays (500 total sheets)",
      "Automatic 2-sided printing & scanning",
      "4.3-inch intuitive color touchscreen"
    ],
    "specifications": {
      "Print Technology": "Thermal Inkjet",
      "Functions": "Print, Copy, Scan, Fax",
      "Brand": "HP",
      "Category": "Inkjet Printers",
      "Connectivity": "Wireless (Wi-Fi), USB 2.0, Mobile App Support",
      "Duplex Printing": "Automatic 2-Sided",
      "Paper Handling": "Dual 250-sheet paper trays (500 total sheets)"
    },
    "slug": "hp-officejet-pro-9730e-wide-format-wireless-color-all-in-one-printer"
  },
  {
    "id": "PV-042",
    "numericId": 42,
    "sku": "PV-042",
    "name": "HP Smart Tank 6001 Wireless Color All-in-One Ink Tank Printer",
    "category": "Inkjet Printers",
    "brand": "HP",
    "price": 299.99,
    "oldPrice": 369.99,
    "regularPrice": 369.99,
    "salePrice": 299.99,
    "discount": 19,
    "rating": "4.7",
    "reviews": 189,
    "badge": "Special Deal",
    "stock": true,
    "printTech": "Cartridge-Free Smart Tank",
    "type": "printer",
    "svgAccent": "#059669",
    "image": "images/products/hp-smart-tank-7602.jpg",
    "description": "Refillable cartridge-free Smart Tank printer with up to 2 years of ink included, automatic 2-sided printing, and smart-guided buttons.",
    "features": [
      "Up to 2 years of ink included in box",
      "Auto 2-sided printing",
      "Smart-guided buttons with status lights",
      "Self-healing Wi-Fi connection"
    ],
    "specifications": {
      "Print Technology": "Cartridge-Free Smart Tank",
      "Functions": "Print, Copy, Scan",
      "Brand": "HP",
      "Category": "Inkjet Printers",
      "Connectivity": "Wireless (Wi-Fi), USB 2.0, Mobile App Support",
      "Duplex Printing": "Automatic 2-Sided",
      "Paper Handling": "Standard Input Tray"
    },
    "slug": "hp-smart-tank-6001-wireless-color-all-in-one-ink-tank-printer"
  },
  {
    "id": "PV-043",
    "numericId": 43,
    "sku": "PV-043",
    "name": "HP Smart Tank 7301 Wireless Color All-in-One Ink Tank Printer",
    "category": "Inkjet Printers",
    "brand": "HP",
    "price": 369.99,
    "oldPrice": 449.99,
    "regularPrice": 449.99,
    "salePrice": 369.99,
    "discount": 18,
    "rating": "4.8",
    "reviews": 46,
    "badge": "Special Deal",
    "stock": true,
    "printTech": "Cartridge-Free Smart Tank",
    "type": "printer",
    "svgAccent": "#059669",
    "image": "images/products/hp-smart-tank-7602.jpg",
    "description": "High-capacity Smart Tank printer featuring a 35-sheet auto document feeder, 250-sheet paper tray, and fast document printing speeds.",
    "features": [
      "35-sheet auto document feeder",
      "250-sheet input paper tray",
      "Up to 2 years of ink included",
      "Print speeds up to 15 ppm black / 9 ppm color"
    ],
    "specifications": {
      "Print Technology": "Cartridge-Free Smart Tank",
      "Functions": "Print, Copy, Scan",
      "Brand": "HP",
      "Category": "Inkjet Printers",
      "Connectivity": "Wireless (Wi-Fi), USB 2.0, Mobile App Support",
      "Duplex Printing": "Manual",
      "Paper Handling": "35-sheet auto document feeder"
    },
    "slug": "hp-smart-tank-7301-wireless-color-all-in-one-ink-tank-printer"
  },
  {
    "id": "PV-044",
    "numericId": 44,
    "sku": "PV-044",
    "name": "HP Smart Tank 7602 Wireless Color All-in-One Ink Tank Printer, Scan, Copy, Fax",
    "category": "Inkjet Printers",
    "brand": "HP",
    "price": 379.99,
    "oldPrice": 469.99,
    "regularPrice": 469.99,
    "salePrice": 379.99,
    "discount": 19,
    "rating": "4.9",
    "reviews": 53,
    "badge": "Special Deal",
    "stock": true,
    "printTech": "Cartridge-Free Smart Tank",
    "type": "printer",
    "svgAccent": "#059669",
    "image": "images/products/hp-smart-tank-7602.jpg",
    "description": "Top-of-the-line Smart Tank all-in-one printer featuring modern touch screen control, fax capability, ADF, and 2 years of ink out of the box.",
    "features": [
      "3-inch magic touch display screen",
      "Full Print, Copy, Scan, Fax functionality",
      "35-sheet auto document feeder",
      "Up to 8,000 color or 6,000 black pages included"
    ],
    "specifications": {
      "Print Technology": "Cartridge-Free Smart Tank",
      "Functions": "Print, Copy, Scan, Fax",
      "Brand": "HP",
      "Category": "Inkjet Printers",
      "Connectivity": "Wireless (Wi-Fi), USB 2.0, Mobile App Support",
      "Duplex Printing": "Manual",
      "Paper Handling": "35-sheet auto document feeder"
    },
    "slug": "hp-smart-tank-7602-wireless-color-all-in-one-ink-tank-printer-scan-copy-fax"
  }
];

// Expose globally for both Browser and Node module environments if applicable
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { PRODUCTS };
}
