const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const projectDir = 'c:/Users/naven/Desktop/printersvault';

console.log('==================================================');
console.log('PRINTERSVAULT SECURITY & MALWARE AUDIT SCANNER');
console.log('==================================================');

// Helper to recursively get all files
function getAllFiles(dirPath, arrayOfFiles = []) {
  const files = fs.readdirSync(dirPath);
  files.forEach(file => {
    const filePath = path.join(dirPath, file);
    if (fs.statSync(filePath).isDirectory()) {
      if (!filePath.includes('node_modules') && !filePath.includes('.git') && !filePath.includes('scratch')) {
        getAllFiles(filePath, arrayOfFiles);
      }
    } else {
      arrayOfFiles.push(filePath);
    }
  });
  return arrayOfFiles;
}

const allFiles = getAllFiles(projectDir);
console.log(`Total production & asset files found: ${allFiles.length}`);

// 1. AI & Dev Tool References Scan
console.log('\n--- 1. SCANNING FOR AI & DEV TOOL REFERENCES ---');
const devTerms = [
  'chatgpt', 'openai', 'claude', 'gemini', 'cursor', 'lovable', 'bolt',
  'v0', 'replit', 'generated by ai', 'ai generated', 'artificial intelligence',
  'prompt engineering', 'localhost', '127.0.0.1', 'test.com', 'example.com',
  'todo:', 'fixme:', 'debug:', 'temp:'
];

allFiles.forEach(file => {
  const rel = path.relative(projectDir, file);
  const ext = path.extname(file).toLowerCase();
  if (['.html', '.css', '.js', '.json', '.htaccess', '.md'].includes(ext) || file.endsWith('.htaccess')) {
    const content = fs.readFileSync(file, 'utf8');
    const lines = content.split('\n');
    lines.forEach((line, idx) => {
      devTerms.forEach(term => {
        if (line.toLowerCase().includes(term)) {
          // Check context: filter out legitimate business text if any
          console.log(`[DEV-REF] ${rel}:${idx+1} -> found "${term}": ${line.trim().substring(0, 100)}`);
        }
      });
    });
  }
});

// 2. Suspicious & Malicious Code Patterns
console.log('\n--- 2. SCANNING FOR SUSPICIOUS / MALICIOUS CODE PATTERNS ---');
const suspiciousPatterns = [
  { name: 'eval()', regex: /\beval\s*\(/g },
  { name: 'new Function()', regex: /new\s+Function\s*\(/g },
  { name: 'document.write', regex: /document\.write\s*\(/g },
  { name: 'atob / btoa', regex: /\b(atob|btoa)\s*\(/g },
  { name: 'String.fromCharCode', regex: /String\.fromCharCode/g },
  { name: 'unescape', regex: /\bunescape\s*\(/g },
  { name: 'hex/unicode escapes in strings', regex: /(\\x[0-9a-fA-F]{2}){3,}|(\\u[0-9a-fA-F]{4}){3,}/g },
  { name: 'sendBeacon', regex: /navigator\.sendBeacon/g },
  { name: 'WebSocket', regex: /new\s+WebSocket/g },
  { name: 'crypto miner patterns', regex: /(coinhive|cryptonight|miner)/gi },
  { name: 'hidden iframe', regex: /<iframe[^>]*style=["'][^"']*(display:\s*none|visibility:\s*hidden|width:\s*0|height:\s*0)/gi }
];

allFiles.forEach(file => {
  const rel = path.relative(projectDir, file);
  const ext = path.extname(file).toLowerCase();
  if (['.html', '.js', '.svg'].includes(ext)) {
    const content = fs.readFileSync(file, 'utf8');
    suspiciousPatterns.forEach(pattern => {
      if (pattern.regex.test(content)) {
        console.log(`[SUSPICIOUS PATTERN] ${rel} -> ${pattern.name}`);
      }
    });
  }
});

// 3. External Resources & Domains Scan
console.log('\n--- 3. SCANNING EXTERNAL RESOURCES & DOMAINS ---');
const externalUrls = new Set();
const scriptSources = [];
const linkTargets = [];

allFiles.forEach(file => {
  const rel = path.relative(projectDir, file);
  const ext = path.extname(file).toLowerCase();
  if (['.html', '.js', '.css'].includes(ext)) {
    const content = fs.readFileSync(file, 'utf8');
    
    // Find script src
    const scriptMatches = content.matchAll(/<script[^>]+src=["']([^"']+)["']/gi);
    for (const m of scriptMatches) {
      scriptSources.push({ file: rel, src: m[1] });
      if (m[1].startsWith('http:') || m[1].startsWith('https:') || m[1].startsWith('//')) {
        externalUrls.add(m[1]);
      }
    }

    // Find all http/https URLs
    const urlMatches = content.matchAll(/https?:\/\/[^\s"'<>)]+/gi);
    for (const m of urlMatches) {
      externalUrls.add(m[0]);
    }

    // Find target="_blank" links without rel="noopener noreferrer"
    if (ext === '.html') {
      const targetMatches = content.matchAll(/<a[^>]+target=["']_blank["'][^>]*>/gi);
      for (const m of targetMatches) {
        if (!m[0].includes('rel=') || !m[0].includes('noopener')) {
          linkTargets.push({ file: rel, tag: m[0] });
        }
      }
    }
  }
});

console.log('Script Sources Found:', scriptSources);
console.log('External URLs Found:', Array.from(externalUrls));
console.log(`target="_blank" links missing rel="noopener noreferrer": ${linkTargets.length}`);
if (linkTargets.length > 0) {
  linkTargets.slice(0, 10).forEach(l => console.log(`  ${l.file}: ${l.tag}`));
}

// 4. Redirects Scan
console.log('\n--- 4. SCANNING FOR REDIRECTS & LOCATION MANIPULATION ---');
allFiles.forEach(file => {
  const rel = path.relative(projectDir, file);
  const ext = path.extname(file).toLowerCase();
  if (['.js', '.html'].includes(ext)) {
    const content = fs.readFileSync(file, 'utf8');
    const lines = content.split('\n');
    lines.forEach((line, idx) => {
      if (line.match(/(location\.href|location\.replace|location\.assign|window\.location|meta\s+http-equiv=["']refresh["'])/i)) {
        console.log(`[REDIRECT] ${rel}:${idx+1} -> ${line.trim()}`);
      }
    });
  }
});

// 5. Secret / Credentials / Console.log Scan
console.log('\n--- 5. SCANNING FOR SECRETS & CONSOLE LOGS ---');
const secretRegex = /(api[_-]?key|secret|password|private[_-]?key|access[_-]?token|jwt[_-]?secret)\s*[:=]\s*["'][^"']{8,}["']/gi;

allFiles.forEach(file => {
  const rel = path.relative(projectDir, file);
  const ext = path.extname(file).toLowerCase();
  if (['.js', '.html', '.json'].includes(ext)) {
    const content = fs.readFileSync(file, 'utf8');
    const lines = content.split('\n');
    lines.forEach((line, idx) => {
      if (secretRegex.test(line)) {
        console.log(`[POSSIBLE SECRET] ${rel}:${idx+1} -> ${line.trim().substring(0, 60)}`);
      }
      if (line.includes('console.log') || line.includes('console.error')) {
        if (line.toLowerCase().includes('pass') || line.toLowerCase().includes('user') || line.toLowerCase().includes('token')) {
          console.log(`[SENSITIVE LOG] ${rel}:${idx+1} -> ${line.trim()}`);
        }
      }
    });
  }
});

// 6. SVG Security Audit
console.log('\n--- 6. SCANNING SVG FILES FOR INLINE SCRIPTS ---');
allFiles.forEach(file => {
  const rel = path.relative(projectDir, file);
  if (file.endsWith('.svg')) {
    const content = fs.readFileSync(file, 'utf8');
    if (content.toLowerCase().includes('<script') || content.toLowerCase().includes('onload=') || content.toLowerCase().includes('onerror=')) {
      console.log(`[SVG SECURITY RISK] ${rel} contains script or event handlers!`);
    }
  }
});

// 7. Spam Terms Scan
console.log('\n--- 7. SCANNING FOR SEO SPAM / HACKED CONTENT ---');
const spamTerms = ['casino', 'poker', 'viagra', 'cialis', 'payday loan', 'replica', 'adult', 'gambling'];
allFiles.forEach(file => {
  const rel = path.relative(projectDir, file);
  const ext = path.extname(file).toLowerCase();
  if (['.html', '.js'].includes(ext)) {
    const content = fs.readFileSync(file, 'utf8');
    spamTerms.forEach(term => {
      if (content.toLowerCase().includes(term)) {
        console.log(`[SPAM TERM] ${rel} -> contains "${term}"`);
      }
    });
  }
});
